# Generated by Django 5.2.17 on 2026-09-18 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название трека')),
                ('bpm', models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='Темп (BPM)')),
                ('musical_key', models.CharField(blank=True, max_length=30, verbose_name='Тональность')),
                ('stage', models.CharField(choices=[('idea', 'Идея'), ('arrangement', 'Аранжировка'), ('mixing', 'Сведение'), ('mastering', 'Мастеринг'), ('done', 'Готово')], default='idea', max_length=20, verbose_name='Этап')),
                ('notes', models.TextField(blank=True, max_length=4000, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Задача')),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracks.project')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
